feat(deps): update default Node.js to 24.14.0 (#569)
* feat(deps): update default Node.js to 24.14.0

Update circleci/browser-tools to 2.4.0

* corrected missing browser-tools update

diff --git a/.circleci/test-deploy.yml b/.circleci/test-deploy.yml
--- a/.circleci/test-deploy.yml
+++ b/.circleci/test-deploy.yml
@@ -1,7 +1,7 @@
 version: 2.1
 orbs:
   orb-tools: circleci/orb-tools@12.4.0 # https://circleci.com/developer/orbs/orb/circleci/orb-tools
-  browser-tools: circleci/browser-tools@2.3.2 # https://circleci.com/developer/orbs/orb/circleci/browser-tools
+  browser-tools: circleci/browser-tools@2.4.0 # https://circleci.com/developer/orbs/orb/circleci/browser-tools
   # The orb will be injected here by the "continue" job.
 filters: &filters
   tags:
@@ -85,10 +85,10 @@ workflows:
           name: Custom Node Version Example
           working-directory: examples/npm-install
           cypress-cache-key: cypress-cache-{{ arch }}-{{ checksum "examples/npm-install/package.json" }}
-          node-version: "24.13.1"
+          node-version: "24.14.0"
           post-install: |
-            if ! node --version | grep -q "24.13.1"; then
-                echo "Node.js version 24.13.1 not found"
+            if ! node --version | grep -q "24.14.0"; then
+                echo "Node.js version 24.14.0 not found"
                 exit 1
             fi
       - cypress/run:
