fix: show good error message if package-lock.json file is missing

diff --git a/src/orb.yml b/src/orb.yml
--- a/src/orb.yml
+++ b/src/orb.yml
@@ -85,6 +85,15 @@ commands:
           condition: << parameters.yarn >>
           steps:
             - run:
+                name: 'Check if package-lock.json exists'
+                command: |
+                  if [ ! -e ./package-lock.json ]; then
+                    echo "The Cypress orb uses 'npm ci' to install 'node_modules', which requires a 'package-lock.json'."
+                    echo "A 'package-lock.json' file was not found. Please run 'npm install' in your project,"
+                    echo "and commit 'package-lock.json' to your repo."
+                    exit 1
+                  fi
+            - run:
                 name: 'Npm CI'
                 command: 'npm ci'
       - run: npx cypress verify
